<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup Label="Branding">
    <PackageVersion Include="Figgle.Fonts" Version="0.6.6" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>
  <ItemGroup Label="ApiDocumentation">
    <PackageVersion Include="Scalar.AspNetCore" Version="2.17.10" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup Label="ApiVersioning">
    <PackageVersion Include="Asp.Versioning.Http" Version="10.2.3" />
    <PackageVersion Include="Asp.Versioning.OpenApi" Version="10.2.3" />
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
  </ItemGroup>
  <ItemGroup Label="Persistence">
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup Label="Validation">
    <PackageVersion Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>
</Project>