<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>884a2b38-1865-4a94-8e34-91d625681dc9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\ChromaLoom.Modules\ChromaLoom.Modules.csproj" />
    <ProjectReference Include="..\ChromaLoom.Infrastructure\ChromaLoom.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup Label="External Packages">
    <!-- Branding -->
    <PackageReference Include="Figgle.Fonts" />
    <PackageReference Include="Spectre.Console" />

    <!-- ApiDocumentation -->
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />

    <!-- ApiVersioning -->
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.OpenApi" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
  </ItemGroup>

</Project>